export const THINKING_WORDS = [
  'Waffling',
  'Overtweaking',
  'Catastrophizing',
  'Spiraling',
  'Hedging',
  'Faffing',
  'Kerfuffling',
  'Whatchamacalliting',
  'Discombobulating',
  'Bouncing',
  'Guesstimating',
  'zesting',
  'julienning',
  'Cringing',
  'Gerrymandering',
  'Schlepping',
  'Doing hard yakka',
  'Caffeinating',
  'Levitating',
  'Overdosing',
  'Burning rainforests',
  'Reticulating',
  'Chronographing',
  'Skedaddling',
  'sensing',
  'Cooking',
  'Combobulating',
  'Existentialising',
  'jojoing',
  'Dancing',
  'Lolotte',
  'Gallivanting',
  'pruning',
  'Flexing',
  'tomfoolering',
  'Moremoring',
  'Bakajiking',
  'glazing',
  'Having a geez',
  'Osmosing',
  'Tokening',
  'Mulling',
  'Gagging gracefully',
  'wasting',
  'Waiting longer just for the hell of it',
  'Turning heads and stomachs',
  'canoodling',
  'Razzmatazzing',
  'Flibbertigibbeting',
  'caramelizing onions',
  'Moonwalking',
  'Flibbertigibetting',
  'Stupentifying',
  'Booping',
  'Sloppening',
  'incubating',
  'Partying',
  'Sauteeing',
  'Arneling',
  'Guzzling',
  'cogitated',
  'Believing in you',
  'finagling',
  'Curling',
  'buzzing',
  'Twinkling',
  'Arnelling',
  'honking',
  'bruhing',
  'Gliding',
  'Fishing',
  'Wrangling',
  'Evaporating',
  'hullabalooing',
];

export function getRandomThinkingWord() {
  return THINKING_WORDS[Math.floor(Math.random() * THINKING_WORDS.length)];
}
